/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./hl.g
 *     -                            On : 2019-08-11 19:22:30
 *     -                 for the lexer : hlLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "hlLexer.h"
/* ----------------------------------------- */


/** String literals used by hlLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x70, 0x72, 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3D, 0x3C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x3D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x7B, 0x7D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   phlLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  phlLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->phlLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->phlLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__27    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__28    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__29    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__30    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__31    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mPRINT    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mEQ    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mNE    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mLITTLE    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mGT    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mLE    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mEL    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mGE    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mEG    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mOR    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mAND    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mIF    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mMINUS    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mTIMES    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mDOT    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mASSIGN    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mBLOCK    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mDEF    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mNEWLINE    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (phlLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (phlLexer ctx);
static void	hlLexerFree(phlLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
hlLexerFree  (phlLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
hlLexerReset (phlLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./hl.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called hlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success phlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API phlLexer hlLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return hlLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called hlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success phlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API phlLexer hlLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    phlLexer ctx; // Context structure we will build and return

    ctx = (phlLexer) ANTLR3_CALLOC(1, sizeof(hlLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in hlLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our hlLexer interface
     */
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mPRINT	= mPRINT;
    ctx->mEQ	= mEQ;
    ctx->mNE	= mNE;
    ctx->mLITTLE	= mLITTLE;
    ctx->mGT	= mGT;
    ctx->mLE	= mLE;
    ctx->mEL	= mEL;
    ctx->mGE	= mGE;
    ctx->mEG	= mEG;
    ctx->mOR	= mOR;
    ctx->mAND	= mAND;
    ctx->mIF	= mIF;
    ctx->mPLUS	= mPLUS;
    ctx->mMINUS	= mMINUS;
    ctx->mTIMES	= mTIMES;
    ctx->mDOT	= mDOT;
    ctx->mASSIGN	= mASSIGN;
    ctx->mBLOCK	= mBLOCK;
    ctx->mDEF	= mDEF;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mNEWLINE	= mNEWLINE;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= hlLexerFree;
    ctx->reset          = hlLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;


    // ./hl.g:7:7: ( '(' )
    // ./hl.g:7:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 8:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;


    // ./hl.g:8:7: ( ')' )
    // ./hl.g:8:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 9:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;


    // ./hl.g:9:7: ( ';' )
    // ./hl.g:9:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 10:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;


    // ./hl.g:10:7: ( '{' )
    // ./hl.g:10:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 11:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;


    // ./hl.g:11:7: ( '}' )
    // ./hl.g:11:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 68:6: ( 'print' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PRINT
 *
 * Looks to match the characters the constitute the token PRINT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPRINT(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PRINT;


    // ./hl.g:68:6: ( 'print' )
    // ./hl.g:68:8: 'print'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto rulePRINTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePRINTEx; /* Prevent compiler warnings */
    rulePRINTEx: ;

}
// $ANTLR end PRINT

//   Comes from: 69:4: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQ
 *
 * Looks to match the characters the constitute the token EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQ(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQ;


    // ./hl.g:69:4: ( '==' )
    // ./hl.g:69:6: '=='
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEx; /* Prevent compiler warnings */
    ruleEQEx: ;

}
// $ANTLR end EQ

//   Comes from: 70:4: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NE
 *
 * Looks to match the characters the constitute the token NE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNE(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NE;


    // ./hl.g:70:4: ( '!=' )
    // ./hl.g:70:6: '!='
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleNEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEEx; /* Prevent compiler warnings */
    ruleNEEx: ;

}
// $ANTLR end NE

//   Comes from: 71:8: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LITTLE
 *
 * Looks to match the characters the constitute the token LITTLE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLITTLE(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LITTLE;


    // ./hl.g:71:8: ( '<' )
    // ./hl.g:71:10: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleLITTLEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLITTLEEx; /* Prevent compiler warnings */
    ruleLITTLEEx: ;

}
// $ANTLR end LITTLE

//   Comes from: 72:4: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GT
 *
 * Looks to match the characters the constitute the token GT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGT(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GT;


    // ./hl.g:72:4: ( '>' )
    // ./hl.g:72:6: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleGTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGTEx; /* Prevent compiler warnings */
    ruleGTEx: ;

}
// $ANTLR end GT

//   Comes from: 73:4: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LE
 *
 * Looks to match the characters the constitute the token LE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLE(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LE;


    // ./hl.g:73:4: ( '<=' )
    // ./hl.g:73:6: '<='
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleLEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLEEx; /* Prevent compiler warnings */
    ruleLEEx: ;

}
// $ANTLR end LE

//   Comes from: 74:4: ( '=<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EL
 *
 * Looks to match the characters the constitute the token EL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEL(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EL;


    // ./hl.g:74:4: ( '=<' )
    // ./hl.g:74:6: '=<'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleELEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleELEx; /* Prevent compiler warnings */
    ruleELEx: ;

}
// $ANTLR end EL

//   Comes from: 75:4: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GE
 *
 * Looks to match the characters the constitute the token GE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGE(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GE;


    // ./hl.g:75:4: ( '>=' )
    // ./hl.g:75:6: '>='
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleGEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGEEx; /* Prevent compiler warnings */
    ruleGEEx: ;

}
// $ANTLR end GE

//   Comes from: 76:4: ( '=>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EG
 *
 * Looks to match the characters the constitute the token EG
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEG(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EG;


    // ./hl.g:76:4: ( '=>' )
    // ./hl.g:76:6: '=>'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleEGEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEGEx; /* Prevent compiler warnings */
    ruleEGEx: ;

}
// $ANTLR end EG

//   Comes from: 77:4: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OR
 *
 * Looks to match the characters the constitute the token OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOR(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OR;


    // ./hl.g:77:4: ( '||' )
    // ./hl.g:77:6: '||'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOREx; /* Prevent compiler warnings */
    ruleOREx: ;

}
// $ANTLR end OR

//   Comes from: 78:4: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AND
 *
 * Looks to match the characters the constitute the token AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mAND(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = AND;


    // ./hl.g:78:4: ( '&&' )
    // ./hl.g:78:6: '&&'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleANDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleANDEx; /* Prevent compiler warnings */
    ruleANDEx: ;

}
// $ANTLR end AND

//   Comes from: 79:3: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IF
 *
 * Looks to match the characters the constitute the token IF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIF(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IF;


    // ./hl.g:79:3: ( 'if' )
    // ./hl.g:79:5: 'if'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleIFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIFEx; /* Prevent compiler warnings */
    ruleIFEx: ;

}
// $ANTLR end IF

//   Comes from: 80:5: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // ./hl.g:80:5: ( '+' )
    // ./hl.g:80:7: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 81:6: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MINUS;


    // ./hl.g:81:6: ( '-' )
    // ./hl.g:81:8: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 82:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TIMES
 *
 * Looks to match the characters the constitute the token TIMES
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTIMES(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TIMES;


    // ./hl.g:82:6: ( '*' )
    // ./hl.g:82:8: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleTIMESEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTIMESEx; /* Prevent compiler warnings */
    ruleTIMESEx: ;

}
// $ANTLR end TIMES

//   Comes from: 83:5: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOT(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DOT;


    // ./hl.g:83:5: ( ',' )
    // ./hl.g:83:7: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleDOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 84:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGN
 *
 * Looks to match the characters the constitute the token ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGN(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ASSIGN;


    // ./hl.g:84:7: ( '=' )
    // ./hl.g:84:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleASSIGNEx; /* Prevent compiler warnings */
    ruleASSIGNEx: ;

}
// $ANTLR end ASSIGN

//   Comes from: 85:6: ( '{}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BLOCK
 *
 * Looks to match the characters the constitute the token BLOCK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBLOCK(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BLOCK;


    // ./hl.g:85:6: ( '{}' )
    // ./hl.g:85:8: '{}'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleBLOCKEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBLOCKEx; /* Prevent compiler warnings */
    ruleBLOCKEx: ;

}
// $ANTLR end BLOCK

//   Comes from: 86:4: ( 'd' 'e' 'f' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DEF
 *
 * Looks to match the characters the constitute the token DEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDEF(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DEF;


    // ./hl.g:86:4: ( 'd' 'e' 'f' )
    // ./hl.g:86:6: 'd' 'e' 'f'
    {
        MATCHC('d');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


        MATCHC('e');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


        MATCHC('f');
        if  (HASEXCEPTION())
        {
            goto ruleDEFEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDEFEx; /* Prevent compiler warnings */
    ruleDEFEx: ;

}
// $ANTLR end DEF

//   Comes from: 87:3: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | '0' .. '9' | 'A' .. 'Z' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // ./hl.g:87:3: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | '0' .. '9' | 'A' .. 'Z' | '_' )* )
    // ./hl.g:87:5: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | '0' .. '9' | 'A' .. 'Z' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDEx;
        }


        // ./hl.g:87:29: ( 'a' .. 'z' | '0' .. '9' | 'A' .. 'Z' | '_' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // ./hl.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 88:4: ( ( '~' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // ./hl.g:88:4: ( ( '~' )? ( '0' .. '9' )+ )
    // ./hl.g:88:6: ( '~' )? ( '0' .. '9' )+
    {
        // ./hl.g:88:6: ( '~' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '~':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // ./hl.g:88:6: '~'
        	    {
        	        MATCHC('~');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	    }
        	    break;

            }
        }

        // ./hl.g:88:11: ( '0' .. '9' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // ./hl.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 89:8: ( ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEWLINE
 *
 * Looks to match the characters the constitute the token NEWLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEWLINE(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEWLINE;


    // ./hl.g:89:8: ( ( '\\r' )? '\\n' )
    // ./hl.g:89:10: ( '\\r' )? '\\n'
    {
        // ./hl.g:89:10: ( '\\r' )?
        {
            int alt4=2;
            switch ( LA(1) )
            {
                case '\r':
                	{
                		alt4=1;
                	}
                    break;
            }

            switch (alt4)
            {
        	case 1:
        	    // ./hl.g:89:10: '\\r'
        	    {
        	        MATCHC('\r');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\n');
        if  (HASEXCEPTION())
        {
            goto ruleNEWLINEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEWLINEEx; /* Prevent compiler warnings */
    ruleNEWLINEEx: ;

}
// $ANTLR end NEWLINE

//   Comes from: 90:4: ( ( ' ' | '\\t' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(phlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // ./hl.g:90:4: ( ( ' ' | '\\t' )+ )
    // ./hl.g:90:6: ( ' ' | '\\t' )+
    {
        // ./hl.g:90:6: ( ' ' | '\\t' )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case ' ':
        		{
        			alt5=1;
        		}
        	    break;

        	}

        	switch (alt5)
        	{
        	    case 1:
        	        // ./hl.g:
        	        {
        	            if ( LA(1) == '\t' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(phlLexer ctx)
{
    {
        //  ./hl.g:1:8: ( T__27 | T__28 | T__29 | T__30 | T__31 | PRINT | EQ | NE | LITTLE | GT | LE | EL | GE | EG | OR | AND | IF | PLUS | MINUS | TIMES | DOT | ASSIGN | BLOCK | DEF | ID | INT | NEWLINE | WS )

        ANTLR3_UINT32 alt6;

        alt6=28;

        switch ( LA(1) )
        {
        case '(':
        	{
        		alt6=1;
        	}
            break;
        case ')':
        	{
        		alt6=2;
        	}
            break;
        case ';':
        	{
        		alt6=3;
        	}
            break;
        case '{':
        	{
        		switch ( LA(2) )
        		{
        		case '}':
        			{
        				alt6=23;
        			}
        		    break;

        		default:
        		    alt6=4;
        		}

        	}
            break;
        case '}':
        	{
        		alt6=5;
        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'r':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 't':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=25;
        											}
        										    break;

        										default:
        										    alt6=6;
        										}

        									}
        								    break;

        								default:
        								    alt6=25;
        								}

        							}
        						    break;

        						default:
        						    alt6=25;
        						}

        					}
        				    break;

        				default:
        				    alt6=25;
        				}

        			}
        		    break;

        		default:
        		    alt6=25;
        		}

        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=7;
        			}
        		    break;
        		case '<':
        			{
        				alt6=12;
        			}
        		    break;
        		case '>':
        			{
        				alt6=14;
        			}
        		    break;

        		default:
        		    alt6=22;
        		}

        	}
            break;
        case '!':
        	{
        		alt6=8;
        	}
            break;
        case '<':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=11;
        			}
        		    break;

        		default:
        		    alt6=9;
        		}

        	}
            break;
        case '>':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt6=13;
        			}
        		    break;

        		default:
        		    alt6=10;
        		}

        	}
            break;
        case '|':
        	{
        		alt6=15;
        	}
            break;
        case '&':
        	{
        		alt6=16;
        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt6=25;
        					}
        				    break;

        				default:
        				    alt6=17;
        				}

        			}
        		    break;

        		default:
        		    alt6=25;
        		}

        	}
            break;
        case '+':
        	{
        		alt6=18;
        	}
            break;
        case '-':
        	{
        		alt6=19;
        	}
            break;
        case '*':
        	{
        		alt6=20;
        	}
            break;
        case ',':
        	{
        		alt6=21;
        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'f':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt6=25;
        							}
        						    break;

        						default:
        						    alt6=24;
        						}

        					}
        				    break;

        				default:
        				    alt6=25;
        				}

        			}
        		    break;

        		default:
        		    alt6=25;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt6=25;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '~':
        	{
        		alt6=26;
        	}
            break;
        case '\n':
        case '\r':
        	{
        		alt6=27;
        	}
            break;
        case '\t':
        case ' ':
        	{
        		alt6=28;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt6)
        {
    	case 1:
    	    // ./hl.g:1:10: T__27
    	    {
    	        /* 1:10: T__27 */
    	        mT__27(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ./hl.g:1:16: T__28
    	    {
    	        /* 1:16: T__28 */
    	        mT__28(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // ./hl.g:1:22: T__29
    	    {
    	        /* 1:22: T__29 */
    	        mT__29(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // ./hl.g:1:28: T__30
    	    {
    	        /* 1:28: T__30 */
    	        mT__30(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // ./hl.g:1:34: T__31
    	    {
    	        /* 1:34: T__31 */
    	        mT__31(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // ./hl.g:1:40: PRINT
    	    {
    	        /* 1:40: PRINT */
    	        mPRINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // ./hl.g:1:46: EQ
    	    {
    	        /* 1:46: EQ */
    	        mEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // ./hl.g:1:49: NE
    	    {
    	        /* 1:49: NE */
    	        mNE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // ./hl.g:1:52: LITTLE
    	    {
    	        /* 1:52: LITTLE */
    	        mLITTLE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // ./hl.g:1:59: GT
    	    {
    	        /* 1:59: GT */
    	        mGT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // ./hl.g:1:62: LE
    	    {
    	        /* 1:62: LE */
    	        mLE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // ./hl.g:1:65: EL
    	    {
    	        /* 1:65: EL */
    	        mEL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // ./hl.g:1:68: GE
    	    {
    	        /* 1:68: GE */
    	        mGE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // ./hl.g:1:71: EG
    	    {
    	        /* 1:71: EG */
    	        mEG(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // ./hl.g:1:74: OR
    	    {
    	        /* 1:74: OR */
    	        mOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // ./hl.g:1:77: AND
    	    {
    	        /* 1:77: AND */
    	        mAND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // ./hl.g:1:81: IF
    	    {
    	        /* 1:81: IF */
    	        mIF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // ./hl.g:1:84: PLUS
    	    {
    	        /* 1:84: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // ./hl.g:1:89: MINUS
    	    {
    	        /* 1:89: MINUS */
    	        mMINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // ./hl.g:1:95: TIMES
    	    {
    	        /* 1:95: TIMES */
    	        mTIMES(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // ./hl.g:1:101: DOT
    	    {
    	        /* 1:101: DOT */
    	        mDOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // ./hl.g:1:105: ASSIGN
    	    {
    	        /* 1:105: ASSIGN */
    	        mASSIGN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // ./hl.g:1:112: BLOCK
    	    {
    	        /* 1:112: BLOCK */
    	        mBLOCK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // ./hl.g:1:118: DEF
    	    {
    	        /* 1:118: DEF */
    	        mDEF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // ./hl.g:1:122: ID
    	    {
    	        /* 1:122: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // ./hl.g:1:125: INT
    	    {
    	        /* 1:125: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // ./hl.g:1:129: NEWLINE
    	    {
    	        /* 1:129: NEWLINE */
    	        mNEWLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // ./hl.g:1:137: WS
    	    {
    	        /* 1:137: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
